#ifndef OPERATIONS_DIVISION_H
#define OPERATIONS_DIVISION_H
#include "operations/export.h"  // generated by CMake, defines OPERATIONS_EXPORT

OPERATIONS_EXPORT int operations_divide (int, int);

#endif
