#ifndef OPERATIONS_MULTIPLICATION_H
#define OPERATIONS_MULTIPLICATION_H
#include "operations/export.h"  // generated by CMake, defines OPERATIONS_EXPORT

OPERATIONS_EXPORT int operations_multiply (int, int);

#endif
